# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'NGMacrosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NGMacrosApp
  pod 'SwiftLint', "0.45.1"
  
  target 'NGMacrosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NGMacrosAppUITests' do
    # Pods for testing
  end

end
